app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/makeofferletter/", views.makeformoffer, name="makeformoffer"),
    path("admin/offerletter/", views.formoffer, name="formoffer"),
    path("admin/makeformcertificate/", views.makeformcertificate, name="makeformcertificate"),
    path("admin/certificate/", views.formcertificate, name="formcertificate"),
    path("admin/htmlcertificate/", views.certificate, name="certificate"),
    path("admin/assignment/<str:id>/", views.sendassignment, name="sendassignment"),
    path("admin/interviewDone/<str:id>/", views.interviewDone, name="interviewDone"),
    path("admin/assignmentDone/<str:id>/", views.assignmentDone, name="assignmentDone"),
    path("admin/send-assignment/<str:id>/", views.sendassignmentlast, name="sendassignmentlast"),
    path("admin/assignment/", views.assignmentMail, name="assignment"),
    path("admin/email/temp/", views.mail, name="mail"),
    path("admin/add-type/", views.add_type, name="add_type"),
    path("admin/delete-type/", views.delete_type, name="delete_type"),
    path("assign-save/", views.assign_save, name="assign-save"),
    path("success", views.success, name="success"),
    path("nosuccess/", views.nosuccess, name="nosuccess"),
    path("", views.home, name="home"),
    path("admin/", views.admin, name="admin"),
    path("admin/add/", views.admin_add, name="admin_add"),
    path("admin/hire/<str:id>/", views.hire, name="hire"),
    path("job_details/<str:myid>/", views.job_details, name="job_details"),
    path("apply_job/<str:myid>/", views.apply_job, name="apply_job"),
    path("sign_up/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("question/", views.question_edit_home, name="question_edit_home"),
    path("question/add/<str:myid>/", views.question_edit_add, name="question_edit_add"),
    path("question/delete/<str:myid>/", views.question_edit_delete, name="question_edit_delete"),
    path("question/delete/<str:myid>/<str:delid>/", views.question_edit_delete_main, name="question_edit_delete_main"),
    path("question/update/<str:myid>/", views.question_edit_update, name="question_edit_update"),
    path("question/update/<str:myid>/<str:delid>/", views.question_edit_update_main, name="question_edit_update_main"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobapply/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/superuser', admin.site.urls),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.core.validators import FileExtensionValidator
from datetime import date
from uuid import uuid4
# Create your models here.

class MyManager(BaseUserManager):
    def create_user(self,email,username,password=None):
        if not email:
            raise ValueError("User must have an eamil address")
        if not username:
            raise ValueError("User must have an username")
        
        user = self.model(
            email = self.normalize_email(email),
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,email,username,password):
        user = self.create_user(
            email = self.normalize_email(email),
            username = username,
            password = password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Login_Accounts(AbstractBaseUser):
    username = models.CharField(max_length=30,unique=True)
    email = models.EmailField(verbose_name="email",max_length=255,unique=True)
    date_joined = models.DateTimeField(verbose_name="date joined",auto_now_add=True)
    last_login = models.DateTimeField(verbose_name="last login",auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    password = models.CharField(max_length=16,default="")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = MyManager()

    def has_perm(self,perm,obj=None):
        return self.is_admin
    def has_module_perms(self,perm,obj=None):
        return True
    
class Job(models.Model):
    id = models.UUIDField(auto_created=True,primary_key = True,default = uuid4,editable = False,unique=True)
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField(max_length=200)
    salary = models.FloatField()
    description = models.TextField(max_length=400)
    experience = models.CharField(max_length=100)
    location = models.JSONField()
    skills = models.JSONField()
    creation_date = models.CharField(max_length=30)
    # def __str__(self):
    #     return f'title: {self.title}'

    
class Mcq(models.Model):
    id = models.UUIDField(auto_created =True,primary_key = True,default = uuid4,editable = False,unique=True)
    jobid = models.ForeignKey(Job,on_delete = models.CASCADE)
    question = models.CharField(max_length=1200)
    answer = models.CharField(max_length=240)
    option2 = models.CharField(max_length=240)
    option3 = models.CharField(max_length=240)
    option4 = models.CharField(max_length=240)
    add_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    # def __str__(self):
    #     return f"{self.question} Answer - {self.answer}"



class Apply(models.Model):
    id = models.UUIDField(auto_created=True,primary_key = True,default = uuid4,editable = False,unique=True)
    jobid = models.ForeignKey(Job,on_delete = models.CASCADE)
    f_name = models.CharField(max_length=64,default="")
    l_name = models.CharField(max_length=64,default="")
    gender = models.CharField(max_length=6,default="")
    email_id = models.EmailField(default="",unique=True)
    edu_year = models.CharField(max_length=4,default="")
    skill = models.JSONField()
    edu_collage_name = models.CharField(max_length=120,default="")
    edu_marks = models.CharField(max_length=9,default="",blank=True)
    internship = models.CharField(max_length=2000,default="",blank=True)
    img = models.ImageField(upload_to='img/'+str(date.today()),null=True, blank=True,default="")
    resume = models.FileField(upload_to='resume/'+str(date.today()), validators=[FileExtensionValidator( ['pdf'] ) ],default="")
    apply_date = models.CharField(max_length=30)
    hired = models.IntegerField(default=0)
    interview = models.IntegerField(default=0)
    assignment = models.IntegerField(default=0)
    score = models.IntegerField(default=0)
    # def __str__(self):
    #     return f'name: {self.f_name} {self.l_name} and edu_collage_name: {self.edu_collage_name}'
class Apply_candidate(models.Model):
    customid = models.UUIDField(auto_created=True,default = uuid4,editable = False,unique=True)
    Applyid = models.ForeignKey(Apply,on_delete = models.CASCADE)

class AssignmentTemp(models.Model):
    type = models.CharField(max_length=120, unique=True)
    text = models.CharField(max_length=6010)

class InterviewTemp(models.Model):
    text = models.CharField(max_length=6010)

class EventDb(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    meetUrl = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
# from django.contrib.staticfiles.storage import staticfiles_storage
# class zip(models.Model):
#     zip = models.FileField(upload_to=f'{staticfiles_storage.url(path)}/'+str(date.today()), validators=[FileExtensionValidator( ['pdf'] ) ],default="")

class role(models.Model):
    role = models.CharField(max_length=200)

class skill(models.Model):
    skill = models.CharField(max_length=200)

app/forms.py
from django import forms
import re
from .models import Job,Apply,Login_Accounts,Mcq
from django.core.validators import FileExtensionValidator
from django.contrib.auth.forms import UserCreationForm


class adddata(forms.ModelForm):
    question = forms.CharField(max_length=1200)
    answer = forms.CharField(max_length=240)
    option2 = forms.CharField(max_length=240)
    option3 = forms.CharField(max_length=240)
    option4 = forms.CharField(max_length=240)
    class Meta:
        model = Mcq
        fields = ['question','answer','option2','option3','option4']

class login_form(forms.ModelForm):
    email = forms.EmailField(max_length=255,label="Email Id", widget = forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(min_length=8,max_length=16,label="Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Login_Accounts
        fields = ['email','password']

        


class RegForm(UserCreationForm):
    username = forms.CharField(min_length=4,max_length=255,label="Username", widget = forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=255,label="Email Id", widget = forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(min_length=8,max_length=16,label="Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(min_length=8,max_length=16,label="Re Enter Password", widget = forms.PasswordInput(attrs={'class': 'form-control'}), help_text = "Enter the same password as above, for verification.")

    class Meta:
        model = Login_Accounts
        fields = ['username','email','password1','password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""


    def clean(self):
        super(RegForm, self).clean()
        # print ("here is " + str(self.cleaned_data))
        password = self.cleaned_data['password1']
        try:
            pass2 = self.cleaned_data['password2']
        except:
            pass2 = ""


        pattern = re.compile('[A-Z]')
        pattern2 = re.compile('[a-z]')
        pattern3 = re.compile('[0-9]')
        pattern4 = re.compile('[!@#$%^&*(),.?":{}|<>]')

        if not pattern.search(password) or not pattern2.search(password) or not pattern3.search(password) or not pattern4.search(password):
                list = ['should contain at least one upper case','should contain at least one lower case','should contain at least one digit','should contain at least one Special character']
                self.add_error('password1',list)
                try:
                    del self._errors['password2']
                except:
                    pass

        else:
            if password != pass2:
                error_message = 'Password did not matched. Enter the same password as above'
                field = 'password2'
                # if self._errors['password2']:
                #     del self._errors['password2']
                try:
                    del self._errors['password2']
                except:
                    pass
                self.add_error(field,error_message)
        return self.cleaned_data




    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Login_Accounts.objects.get(email=email)
        except:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")
        

    def clean_username(self):
        username = self.cleaned_data['username']
        print("username "+ str(username))
        try:
            user_name = Login_Accounts.objects.get(username=username)
        except:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")



# LOCATION_COICES = [ ( "AN", "Andaman and Nicobar Islands" ), ( "AP", "Andhra Pradesh" ),
# ( "AR", "Arunachal Pradesh" ), ( "AS", "Assam" ), ( "BR", "Bihar" ), ( "CG", "Chandigarh" ),
# ( "CH", "Chhattisgarh" ), ( "DH", "Dadra and Nagar Haveli" ), ( "DD", "Daman and Diu" ),
# ( "DL", "Delhi" ), ( "GA", "Goa" ), ( "GJ", "Gujarat" ), ( "HR", "Haryana" ),
# ( "HP", "Himachal Pradesh" ), ( "JK", "Jammu and Kashmir" ), ( "JH", "Jharkhand" ),
# ( "KA", "Karnataka" ), ( "KL", "Kerala" ), ( "LD", "Lakshadweep" ), ( "MP", "Madhya Pradesh" ),
# ( "MH", "Maharashtra" ), ( "MN", "Manipur" ), ( "ML", "Meghalaya" ), ( "MZ", "Mizoram" ),
# ( "NL", "Nagaland" ), ( "OR", "Odisha" ), ( "PY", "Puducherry" ), ( "PB", "Punjab" ),
# ( "RJ", "Rajasthan" ), ( "SK", "Sikkim" ), ( "TN", "Tamil Nadu" ), ( "TS", "Telangana" ),
# ( "TR", "Tripura" ), ( "UK", "Uttar Pradesh" ), ( "UP", "Uttarakhand" ),("WB","West Bengal") ]
##admin file
class jobForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['creation_date','skills','location']
class Apply_form(forms.ModelForm):
    resume = forms.FileField(validators=[FileExtensionValidator( ['pdf'] ) ])
    class Meta:
        model = Apply
        fields = ['gender','email_id','edu_year','edu_collage_name','edu_marks','internship','img','resume']
    # def __init__(self, *args, **kwargs):
    #     super(Apply_form, self).__init__(*args, **kwargs)
    #     self.fields['internship'].required = False
    

        

app/templates/page/admin_profile.html
{% extends "main2.html" %}
{% block title %}Add data{% endblock %}
{% block style %}
{% endblock %}
{% block body %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
<div class="container">
    <form action="/admin/add/" method="post">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        <input type="text" class="form-control" name="title" maxlength="200" required id="id_title">
        <div class="row">
            <div class="col-md-4">
                <label for="id_salary">Salary:</label>
                <input type="number" class="form-control" name="salary" step="any" required id="id_salary">
            </div>
            <div class="col-md-4 col-sm-6">
                <label for="id_start_date">Start date:</label>
                <input type="date" class="form-control" name="start_date" required id="id_start_date">
            </div>
            <div class="col-md-4 col-sm-6">
                <label for="id_end_date">End date:</label>
                <input type="date" name="end_date" class="form-control" required id="id_end_date">
            </div>
        </div>
        <label for="id_description">Description:</label>
        <textarea name="description" class="form-control" cols="40" rows="5" maxlength="400" required
            id="id_description">
</textarea>
        <label for="id_experience">Experience:</label>
        <input type="text" class="form-control" name="experience" maxlength="100" required id="id_experience">
        <label for="id_location">Location:</label>
        <select class="selectpicker form-control" name="location" multiple id="id_location" data-live-search="true">
            <option value="Remote">Remote</option>
            <option value="Andaman and Nicobar Islands">Andaman and Nicobar Islands</option>
            <option value="Andhra Pradesh">Andhra Pradesh</option>
            <option value="Arunachal Pradesh">Arunachal Pradesh</option>
            <option value="Assam">Assam</option>
            <option value="Bihar">Bihar</option>
            <option value="Chandigarh">Chandigarh</option>
            <option value="Chhattisgarh">Chhattisgarh</option>
            <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
            <option value="Daman and Diu">Daman and Diu</option>
            <option value="Delhi">Delhi</option>
            <option value="Goa">Goa</option>
            <option value="Gujarat">Gujarat</option>
            <option value="Haryana">Haryana</option>
            <option value="Himachal Pradesh">Himachal Pradesh</option>
            <option value="Jammu and Kashmir">Jammu and Kashmir</option>
            <option value="Jharkhand">Jharkhand</option>
            <option value="Karnataka">Karnataka</option>
            <option value="Kerala">Kerala</option>
            <option value="Lakshadweep">Lakshadweep</option>
            <option value="Madhya Pradesh">Madhya Pradesh</option>
            <option value="Maharashtra">Maharashtra</option>
            <option value="Manipur">Manipur</option>
            <option value="Meghalaya">Meghalaya</option>
            <option value="Mizoram">Mizoram</option>
            <option value="Nagaland">Nagaland</option>
            <option value="Odisha">Odisha</option>
            <option value="Puducherry">Puducherry</option>
            <option value="Punjab">Punjab</option>
            <option value="Rajasthan">Rajasthan</option>
            <option value="Sikkim">Sikkim</option>
            <option value="Tamil Nadu">Tamil Nadu</option>
            <option value="Telangana">Telangana</option>
            <option value="Tripura">Tripura</option>
            <option value="Uttar Pradesh">Uttar Pradesh</option>
            <option value="Uttarakhand">Uttarakhand</option>
            <option value="West Bengal">West Bengal</option>
        </select>
        <label for="id_skills">Skills:</label>
        <select class="selectpicker form-control" name="skills" multiple required id="id_skills"
            data-live-search="true">
        {% for i in skill %}
        <option value="{{i.skill}}">{{i.skill}}</option>
        {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary mt-2">submit</button>
    </form>
</div>

{% endblock %}

app/templates/page/assignTemp.html
{% extends "main2.html" %}
{% block title %}Asignment{% endblock %}
{% block style %}
<style>
    textarea {
        height: 80vh;
    }

    .fa-files-o:hover {
        opacity: 0.5;
    }
</style>
{% endblock %}
{% block body %}
<main>
    <div class="container">
        <div class="row">
            <div class="border border-info mt-1 mb-1 p-2">
                Help Text :- <b>TYPE</b> must be <b>UNIQUE</b>
            </div>
            {% if seetype %}
            <div class="col-auto">
                <form action="/admin/assignment/" method="post">
                    {% csrf_token %}
                    <select class="form-select mt-2" aria-label="Select to add Type" name="type">
                        {% for i in seetype %}
                        <option value={{i.type}}>{{i.type}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-primary mt-2">Show Assignment EMAIL Format</button>
                </form>
            </div>
            {% endif %}
            <div class="col-auto">
                <form action="/admin/add-type/" method="post">
                    {% csrf_token %}
                    <input class="form-control mt-2" name="newType" type="text">
                    <button type="Submit" class="btn btn-success mt-2">Add Type</button>
                </form>
            </div>
            {% if seetype %}
            <div class="col-auto">
                <form action="/admin/delete-type/" method="post">
                    {% csrf_token %}
                    <select class="form-select mt-2" aria-label="Select to delete Type" name="type">
                        {% for i in seetype %}
                        <option value={{i.type}}>{{i.type}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn btn-danger mt-2">Delete Type</button>
                </form>
            </div>
            {% endif %}
        </div>
        {% if typeData %}
        <div class="bg-light p-2 mt-2">
            <form action="/assign-save/" method="post">
                {% csrf_token %}
                <div class="border border-info mt-3 mb-3 p-2">
                    Important Instruction
                    <ul>
                        <li>For adding name add "<span>{name}</span>" <i class="fa fa-files-o px-2"
                            onclick="myFunction(event)" aria-hidden="true"></i></li>
                        <li>For adding email add "<span>{emailid}</span>"" <i class="fa fa-files-o px-2"
                                onclick="myFunction(event)" aria-hidden="true"></i></li>
                    </ul>
                </div>
                <input type="hidden" value="{{typeData.type}}" name="type">
                <lable>Assignment Format FOR TYPE - (<b>"{{typeData.type}}"</b>)</lable>
                <textarea class="form-control" rows="10" name="text">{{typeData.text}}</textarea>
                <button type="submit" class="btn btn-primary mt-2">Submit</button>
            </form>
        </div>
        {% endif %}
    </div>
</main>
{% endblock %}
{% block js %}
<script>
    function myFunction(event) {
        var r = document.createRange();
        r.selectNode(event.currentTarget.previousElementSibling);
        window.getSelection().removeAllRanges();
        window.getSelection().addRange(r);
        document.execCommand('copy');
        window.getSelection().removeAllRanges();
    }
</script>
{% endblock %}

app/templates/page/detail.html
{% extends "main.html" %}
{% block title %}Details{% endblock %}

{% block body %}
<div class="container">
  <h1 class="text-center">{{data.title}}</h1>
  <div class="card">
    <div class="card-body">
      {{data.description}}
      <hr>
      <div class="col-sm-5 col-md-4 col-auto">
        <div class="rounded-pill border p-2 bg-light text-center"><i class="fa fa-map-marker px-1"
            aria-hidden="true"></i>LOCATION</div>
            <div class="text-center">
              {{location}}
          </div>
      </div>
      
      <div class="row mt-4 mb-4">
        <div class="col-auto">
          <div class="rounded-pill border p-2 bg-light"><i class="fa fa-money px-1" aria-hidden="true"></i> SALARY</div>
          <div class="text-center">{{data.salary}} rs.</div>
        </div>
        <div class="col-auto">
          <div class="rounded-pill border p-2 bg-light"><i class="fa fa-calendar-o px-1" aria-hidden="true"></i>APPLY
            TILL</div>
          <div class="text-center">{{data.end_date}}</div>
        </div>
      </div>
      <h5 class="m-2">Experience</h5>
      <div class="mx-3">{{data.experience}}</div>
      <h5 class="m-2">Skill's required</h5>
      <div class="mx-3">{{skills}}</div>
      <div class="mt-3 text-center">
        <a href="/apply_job/{{id}}/" class="card-link"><button class="btn btn-primary"> APPLY </button></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/page/formcertificate.html
{% extends "main2.html" %}
{% block title %}Certificate{% endblock %}
{% block style %}
{% endblock %}
{% block body %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <main class="container">
        <form action="/admin/makeformcertificate/" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="mb-3 col-auto">
                    <label for="" class="form-label">Date of joining</label>
                    <input type="date" name="date" class="form-control" aria-describedby="helpId">
                </div>
                <div class="mb-3 col-auto">
                    <label class="form-label">Internship Months</label>
                    <select name="months" class="form-control">
                        {% for i in range %}
                        <option value="{{i}}">{{i}} months</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="mb-3">
                <label for="" class="form-label">supervisor</label>
                <input type="text" name="supervisor" id="" class="form-control" placeholder=""
                    aria-describedby="helpId">
            </div>
            <label class="form-label">Role</label>
            <select class="selectpicker form-control mt-2 mb-2" name="role" data-live-search="true">
                {% for i in role %}
                <option value="{{i.role}}">{{i.role}}</option>
                {% endfor %}
            </select>
            <div class="mb-3 mt-3">
                <label class="form-label">Applicant</label>
                <select name="applicant" class="selectpicker form-control" multiple data-live-search="true">
                    {% for i in data %}
                    <option value={{i.customid}}>{{i.Applyid.email_id}} and {{i.Applyid.f_name}} {{i.Applyid.l_name}}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </main>
<script type="text/javascript">
    $('.selectpicker').selectpicker();
</script>
{% endblock %}

app/templates/page/home.html
{% extends "main.html" %}
    {% block title %}HOME{% endblock %}

{% block style %}
<style>
    body{
        background-color: var(--bs-light);
    }
    h3 {
        padding: 10px;
    }

    .color-light {
        color: aliceblue;
    }

    .card {
        border: 0;
    }
    .errorcolor{
        background-color: #cfe2ff;
    }
</style>
{% endblock %}
    {% block body %}
    <div class="container">
        {% if score != False %}
        <div class="errorcolor p-3">
            <small>{{score}}</small>
        </div>
        {% endif %}
        <div class="row">
            {% for i in data%}
            <div class="m-3 card col-lg-3 col-sm-5 col-11 ">
                <div class="card-body">
                    <h5 class="card-title">{{i.title}}</h5>
                    <p class="card-text">{{i.description}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">SALARY {{i.salary}} rs.</li>
                    <li class="list-group-item">TILL - {{i.end_date}}</li>
                </ul>
                <div class="card-footer bg-white">
                    <a href="/apply_job/{{i.id}}/" class="card-link"><button class="btn btn-primary"> APPLY </button></a>
                    <a href="/job_details/{{i.id}}/" class="card-link"><button class="btn btn-info">MORE</button></a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

app/templates/page/login.html
{% extends "main.html" %}

{% block title %}LOGIN{% endblock %}


{% block style %}
<style>
  .custom-container {
    max-width: 300px;
    margin: auto;
  }

  .login-error {
    font-size: 10px;
    background-color: #cfe2ff;
    color: black;
    padding: 5px;
  }

  form input[type="submit"] {
    background-color: green;
    color: aliceblue;
  }

  .signup{
    color:black;
  }
  .signup:hover{
    color:blue;
  }
</style>
{% endblock %}
{% block body %}
<main>

  <div class="custom-container">

    <div class="text-center p-3">
      <a class="navbar-brand" href="#"><sub>This</sub>WEB<sup>Page</sup></a>
    </div>
    {% if nologin %}
    <div class="border login-error text-center">{{nologin}}</div>
    {% endif %}
    <form action="/login/" method="post">
      {% csrf_token %}
      <div class="text-muted"></div>


      <div> <label for="id_email">Email Id:</label> <input type="text" name="email" class="form-control" maxlength="255"
          required="" id="id_email">
        <ul>

        </ul>
      </div>

      <div> <label for="id_password">Password:</label> <input type="password" name="password" class="form-control"
          maxlength="16" minlength="8" required="" id="id_password">
        <ul>

        </ul>
      </div>

      <input class="form-control" type="submit" value="Submit">
    </form>
    <div class="text-center mt-3"><a href={% url 'sign_up' %}><span class="signup">Signup instead</span></a></div>
  </div>
</main>
{% endblock %}